version: '3.8'
services:

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: localhost
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - weatherapp_net 
  
  web:
    build: .
    environment:
      - REDIS_HOST=redis
    command: ["./wait-for-it.sh", "redis:6379", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
      - celery
      - celery-beat
    ports:
      - "8000:8000"
    networks:
      - weatherapp_net 

  redis:
    image: redis:latest
    restart: always
    volumes:
      - ./redis_config/redis.conf:/usr/local/redis/redis.conf
    command: ["redis-server", "/usr/local/redis/redis.conf"]
    networks:
      - weatherapp_net
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
      
  celery:
    build: .
    command: ["celery", "-A", "weather", "worker", "--loglevel=info"]
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    networks:
      - weatherapp_net

  celery-beat:
    build: .
    command: ["celery", "-A", "weather", "beat", "--loglevel=info"]
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    networks:
      - weatherapp_net

volumes:
  pgdata:

networks:
  weatherapp_net:
    driver: bridge