# Generated by Django 5.1.4 on 2024-12-19 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DayForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('date', models.DateField()),
                ('day_name', models.CharField(max_length=20)),
                ('max_temp', models.FloatField()),
                ('min_temp', models.FloatField()),
                ('precipitation', models.FloatField()),
                ('windspeed_max', models.FloatField()),
                ('wind_direction', models.CharField(max_length=20)),
                ('forecast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day_forecasts', to='weather_app.forecast')),
            ],
        ),
    ]
