# Generated by Django 5.1.4 on 2024-12-19 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0002_customsession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomSession',
        ),
    ]
