# Generated by Django 5.1.4 on 2024-12-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0003_delete_customsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayforecast',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
